{"code":"ERR_UNHANDLED_REJECTION","level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\". This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\"."}
{"code":"EENVELOPE","command":"API","level":"error","message":"No recipients defined No recipients defined","stack":"Error: No recipients defined\n    at SMTPConnection._formatError (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:790:19)\n    at SMTPConnection._setEnvelope (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:1023:34)\n    at SMTPConnection.send (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:621:14)\n    at sendMessage (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-transport\\index.js:228:28)\n    at D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-transport\\index.js:286:25\n    at SMTPConnection._actionAUTHComplete (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:1578:9)\n    at SMTPConnection.<anonymous> (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:546:26)\n    at SMTPConnection._processResponse (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:969:20)\n    at SMTPConnection._onData (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:755:14)\n    at SMTPConnection._onSocketData (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:193:44)"}
{"code":"EENVELOPE","command":"API","level":"error","message":"No recipients defined No recipients defined","stack":"Error: No recipients defined\n    at SMTPConnection._formatError (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:790:19)\n    at SMTPConnection._setEnvelope (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:1023:34)\n    at SMTPConnection.send (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:621:14)\n    at sendMessage (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-transport\\index.js:228:28)\n    at D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-transport\\index.js:286:25\n    at SMTPConnection._actionAUTHComplete (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:1578:9)\n    at SMTPConnection.<anonymous> (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:546:26)\n    at SMTPConnection._processResponse (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:969:20)\n    at SMTPConnection._onData (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:755:14)\n    at SMTPConnection._onSocketData (D:\\coding\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:193:44)"}
{"code":"ERR_UNHANDLED_REJECTION","level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\". This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\"."}
{"level":"error","message":"Connection already released Connection already released","stack":"Error: Connection already released\n    at Pool.releaseConnection (D:\\coding\\chatwebby\\server\\node_modules\\mysql\\lib\\Pool.js:138:13)\n    at PoolConnection.release (D:\\coding\\chatwebby\\server\\node_modules\\mysql\\lib\\PoolConnection.js:35:15)\n    at Query.<anonymous> (D:\\coding\\chatwebby\\server\\connection\\index.js:37:18)\n    at Query.<anonymous> (D:\\coding\\chatwebby\\server\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\coding\\chatwebby\\server\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\coding\\chatwebby\\server\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\coding\\chatwebby\\server\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.OkPacket (D:\\coding\\chatwebby\\server\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:74:10)\n    at Protocol._parsePacket (D:\\coding\\chatwebby\\server\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\coding\\chatwebby\\server\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)"}
{"level":"error","message":"Cannot read properties of undefined (reading 'rollback') Cannot read properties of undefined (reading 'rollback')","stack":"TypeError: Cannot read properties of undefined (reading 'rollback')\n    at D:\\coding\\chatwebby\\server\\connection\\index.js:36:16\n    at new Promise (<anonymous>)\n    at rollbackTransaction (D:\\coding\\chatwebby\\server\\connection\\index.js:35:10)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:188:9)\n    at Object.update (D:\\coding\\chatwebby\\server\\controllers\\bot-contorller.js:181:7)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async D:\\coding\\chatwebby\\server\\routes\\bot-routes.js:49:5"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"Cannot read properties of undefined (reading 'rollback') Cannot read properties of undefined (reading 'rollback')","stack":"TypeError: Cannot read properties of undefined (reading 'rollback')\n    at D:\\coding\\chatwebby\\server\\connection\\index.js:36:16\n    at new Promise (<anonymous>)\n    at rollbackTransaction (D:\\coding\\chatwebby\\server\\connection\\index.js:35:10)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:187:9)\n    at Object.update (D:\\coding\\chatwebby\\server\\controllers\\bot-contorller.js:181:7)\n    at async D:\\coding\\chatwebby\\server\\routes\\bot-routes.js:49:5"}
{"level":"error","message":"Cannot read properties of undefined (reading 'rollback') Cannot read properties of undefined (reading 'rollback')","stack":"TypeError: Cannot read properties of undefined (reading 'rollback')\n    at D:\\coding\\chatwebby\\server\\connection\\index.js:36:16\n    at new Promise (<anonymous>)\n    at rollbackTransaction (D:\\coding\\chatwebby\\server\\connection\\index.js:35:10)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:187:9)\n    at Object.update (D:\\coding\\chatwebby\\server\\controllers\\bot-contorller.js:181:7)\n    at async D:\\coding\\chatwebby\\server\\routes\\bot-routes.js:49:5"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:399:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (D:\\coding\\chatwebby\\server\\node_modules\\express\\lib\\response.js:278:15)\n    at errorFunction (D:\\coding\\chatwebby\\server\\controllers\\createBot-controller.js:191:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"code":"EAUTH","command":"API","level":"error","message":"Missing credentials for \"PLAIN\" Missing credentials for \"PLAIN\"","stack":"Error: Missing credentials for \"PLAIN\"\n    at SMTPConnection._formatError (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:790:19)\n    at SMTPConnection.login (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:444:38)\n    at F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-transport\\index.js:272:32\n    at SMTPConnection.<anonymous> (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:213:17)\n    at Object.onceWrapper (node:events:627:28)\n    at SMTPConnection.emit (node:events:513:28)\n    at SMTPConnection.emit (node:domain:489:12)\n    at SMTPConnection._actionEHLO (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:1347:14)\n    at SMTPConnection._processResponse (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:969:20)\n    at SMTPConnection._onData (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:755:14)"}
{"code":"EAUTH","command":"API","level":"error","message":"Missing credentials for \"PLAIN\" Missing credentials for \"PLAIN\"","stack":"Error: Missing credentials for \"PLAIN\"\n    at SMTPConnection._formatError (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:790:19)\n    at SMTPConnection.login (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:444:38)\n    at F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-transport\\index.js:272:32\n    at SMTPConnection.<anonymous> (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:213:17)\n    at Object.onceWrapper (node:events:627:28)\n    at SMTPConnection.emit (node:events:513:28)\n    at SMTPConnection.emit (node:domain:489:12)\n    at SMTPConnection._actionEHLO (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:1347:14)\n    at SMTPConnection._processResponse (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:969:20)\n    at SMTPConnection._onData (F:\\chatwebby\\server\\node_modules\\nodemailer\\lib\\smtp-connection\\index.js:755:14)"}
{"code":"ENOENT","errno":-4058,"level":"error","message":"ENOENT: no such file or directory, open 'D:\\coding\\chatwebby\\server\\routes\\test-file.csv' ENOENT: no such file or directory, open 'D:\\coding\\chatwebby\\server\\routes\\test-file.csv'","path":"D:\\coding\\chatwebby\\server\\routes\\test-file.csv","stack":"Error: ENOENT: no such file or directory, open 'D:\\coding\\chatwebby\\server\\routes\\test-file.csv'","syscall":"open"}
{"code":"EENVELOPE","command":"API","level":"error","message":"No recipients defined No recipients defined","stack":"Error: No recipients defined\n    at SMTPConnection._formatError (/home/admin/chatwebby-1/server/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n    at SMTPConnection._setEnvelope (/home/admin/chatwebby-1/server/node_modules/nodemailer/lib/smtp-connection/index.js:1023:34)\n    at SMTPConnection.send (/home/admin/chatwebby-1/server/node_modules/nodemailer/lib/smtp-connection/index.js:621:14)\n    at sendMessage (/home/admin/chatwebby-1/server/node_modules/nodemailer/lib/smtp-transport/index.js:228:28)\n    at /home/admin/chatwebby-1/server/node_modules/nodemailer/lib/smtp-transport/index.js:286:25\n    at SMTPConnection._actionAUTHComplete (/home/admin/chatwebby-1/server/node_modules/nodemailer/lib/smtp-connection/index.js:1578:9)\n    at SMTPConnection.<anonymous> (/home/admin/chatwebby-1/server/node_modules/nodemailer/lib/smtp-connection/index.js:546:26)\n    at SMTPConnection._processResponse (/home/admin/chatwebby-1/server/node_modules/nodemailer/lib/smtp-connection/index.js:969:20)\n    at SMTPConnection._onData (/home/admin/chatwebby-1/server/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)\n    at SMTPConnection._onSocketData (/home/admin/chatwebby-1/server/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)\n    at TLSSocket.emit (node:events:514:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)"}
{"code":"ERR_UNHANDLED_REJECTION","level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\". This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\"."}
{"code":"ERR_UNHANDLED_REJECTION","level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\". This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\"."}
{"code":"ERR_UNHANDLED_REJECTION","level":"error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\". This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\"."}
{"code":"ENOTFOUND","errno":-3008,"fatal":true,"hostname":"mysql","level":"error","message":"getaddrinfo ENOTFOUND mysql getaddrinfo ENOTFOUND mysql","stack":"Error: getaddrinfo ENOTFOUND mysql\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)\n    --------------------\n    at Protocol._enqueue (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Protocol.handshake (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\protocol\\Protocol.js:51:23)\n    at Connection.connect (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\Connection.js:116:18)\n    at Object.<anonymous> (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\models\\child-model.js:9:12)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\controllers\\child-controller.js:1:21)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)","syscall":"getaddrinfo"}
{"code":"ENOTFOUND","errno":-3008,"fatal":true,"hostname":"mysql","level":"error","message":"getaddrinfo ENOTFOUND mysql getaddrinfo ENOTFOUND mysql","stack":"Error: getaddrinfo ENOTFOUND mysql\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)\n    --------------------\n    at Protocol._enqueue (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Protocol.handshake (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\protocol\\Protocol.js:51:23)\n    at Connection.connect (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\Connection.js:116:18)\n    at Object.<anonymous> (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\models\\child-model.js:9:12)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\controllers\\child-controller.js:1:21)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)","syscall":"getaddrinfo"}
{"code":"ENOTFOUND","errno":-3008,"fatal":true,"hostname":"mysql","level":"error","message":"getaddrinfo ENOTFOUND mysql getaddrinfo ENOTFOUND mysql","stack":"Error: getaddrinfo ENOTFOUND mysql\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)\n    --------------------\n    at Protocol._enqueue (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Protocol.handshake (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\protocol\\Protocol.js:51:23)\n    at Connection.connect (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\Connection.js:116:18)\n    at Object.<anonymous> (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\models\\child-model.js:9:12)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\controllers\\child-controller.js:1:21)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)","syscall":"getaddrinfo"}
{"code":"PROTOCOL_CONNECTION_LOST","fatal":true,"level":"error","message":"Connection lost: The server closed the connection. Connection lost: The server closed the connection.","stack":"Error: Connection lost: The server closed the connection.\n    at Protocol.end (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\protocol\\Protocol.js:112:13)\n    at Socket.<anonymous> (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\Connection.js:94:28)\n    at Socket.<anonymous> (C:\\Users\\HP\\Desktop\\Projects\\CBCPipeline\\server\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:530:35)\n    at Socket.emit (node:domain:488:12)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"code":"ECONNRESET","errno":-4077,"fatal":true,"level":"error","message":"read ECONNRESET read ECONNRESET","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)","syscall":"read"}
{"code":"ECONNRESET","errno":-4077,"fatal":true,"level":"error","message":"read ECONNRESET read ECONNRESET","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)","syscall":"read"}
